### ISSUE TITLE
Use of vm-set-default-exception-handler in lib/gtk/error-dialog.scm

### ISSUE THREAD

**Issue by tomonacci** [shirok/Gauche-gtk2#4]
When you run `examples/error-dialog.scm` with Gauche HEAD (`version 0.9.5_pre1`) you get undefined variable error saying `vm-set-default-exception-handler` is missing. According to Gauche's `ChangeLog` it seems it should be replaced with `(with-module gauche.internal %vm-custom-error-reporter-set!)` for version >= 0.9.5.

**Comment by shirok** [comment]
Actually just replacing vm-set-default-exception-handler doesn't work, for we also changed the semantics of Scm_ReportError (invoked in gauche-gtk's callback handling mechanism).  I think we should handle custom error reporting within gauche-gtk.

**Comment by shirok** [comment]
Fix pushed
